# Generated by Django 4.2.2 on 2023-07-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.CharField(choices=[('tourist', '투어리스트'), ('guide', '가이드')], max_length=10),
        ),
    ]
